import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rusty-report-printer'

pipeline {
    agent {
        kubernetes {
            defaultContainer 'rust'
            yaml '''
                spec:
                    containers:
                        - name: node
                          image: node:16.15-alpine3.16
                          command: ["sleep", "infinity"]
                          resources:
                            requests:
                              cpu: 100m
                              memory: 256Mi
                            limits: 2
                            memory: 256Mi
                        - name: rust
                          image: rustlang/rust:nightly-alpine
                          command: ["sleep", "infinity"]
                          resources:
                            requests:
                              cpu: 10m
                              memory: 12Mi
                            limits: 1
                            memory: 12Mi
            '''
        }
    }

    environment {
        GARGO_UNSTABLE_SPARSE_REGISTRY = 'true'
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                container('node') {
                    dir(PROJECT_DIR) {
                        sh './report_generator.js'
                    }
                }
            }
        }

       stage('Install dependencies') {
           steps {
               dir(PROJECT_DIR) {
                   // if we are on alpine, we need to install musl-dev
                   sh 'apk add --no-cache musl-dev=1.2.2-r7'
               }
           }
       }

        stage('Build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'cargo build --locked'
                }
            }
        }

        // Oh no, we can't perform regular Docker Builds on Kubernetes
        /*
        stage('Build Image') {
            environment {
                DOCKER_BUILDKIT = "1"
            }
            steps {
                dir(PROJECT_DIR) {
                    sh 'docker build -t super-report-printer:v0.1.0 .'
                }
            }
        }
         */
    }
}